Implement unit tests for NotificationService
nantonov/PMCS pull request #43
Opened 2022-08-23 12:07 UTC by moltenessence

2022-08-24 11:38 UTC, nantonov approved these changes

2022-08-24 13:15 UTC, Blackolf931 requested changes

2022-08-24 13:15 UTC, Blackolf931 commented on PMCS/Services/NotificationService/Notification.Tests/AutoData/AutoNotificationDataAttribute.cs
> +        private const string testUserId = "1";
move to a separate file

2022-08-24 13:19 UTC, Blackolf931 commented on PMCS/Services/NotificationService/Notification.Tests/UnitTests/NotificationTests.cs
> +            [Frozen] Mock<IEmailService> emailServiceMock,
Please give me a link to read about [Frozen] and etc

2022-08-24 13:23 UTC, moltenessence commented on PMCS/Services/NotificationService/Notification.Tests/UnitTests/NotificationTests.cs
> +            [Frozen] Mock<IEmailService> emailServiceMock,
This video explains how AutoMoq, AutoData actually work: https://www.youtube.com/watch?v=DbK1NVRQZvs&t=2005s

2022-08-24 13:24 UTC, moltenessence commented on PMCS/Services/NotificationService/Notification.Tests/UnitTests/NotificationTests.cs
> +            [Frozen] Mock<IEmailService> emailServiceMock,
Shorter video by the same author: https://www.youtube.com/watch?v=t3s3-Q1gACk

2022-08-25 07:59 UTC, Blackolf931 approved these changes

2022-08-26 06:58 UTC, merged