Add circuit breaker
nantonov/PMCS pull request #59
Opened 2022-09-09 15:34 UTC by moltenessence

2022-09-12 09:35 UTC, Blackolf931 requested changes

2022-09-12 09:35 UTC, Blackolf931 commented on PMCS/Services/ScheduleService/Schedule.Application/ResiliencePolicy/ResilientPolicy.cs
> +                (int)message.StatusCode >= 500 || (int)message.StatusCode == 429).WaitAndRetryAsync(
You can use message.IsSuccessStatusCode instead of this expression (int)message.StatusCode >= 500 || (int)message.StatusCode == 429)

2022-09-12 11:48 UTC, Blackolf931 approved these changes

2022-09-14 07:41 UTC, nantonov approved these changes

2022-09-14 08:16 UTC, merged